<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('tourRoom', 'doctrine');

/**
 * BasetourRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $city
 * @property string $type
 * @property string $latitude
 * @property string $longitude
 * 
 * @method integer  getId()        Returns the current record's "id" value
 * @method string   getName()      Returns the current record's "name" value
 * @method string   getCity()      Returns the current record's "city" value
 * @method string   getType()      Returns the current record's "type" value
 * @method string   getLatitude()  Returns the current record's "latitude" value
 * @method string   getLongitude() Returns the current record's "longitude" value
 * @method tourRoom setId()        Sets the current record's "id" value
 * @method tourRoom setName()      Sets the current record's "name" value
 * @method tourRoom setCity()      Sets the current record's "city" value
 * @method tourRoom setType()      Sets the current record's "type" value
 * @method tourRoom setLatitude()  Sets the current record's "latitude" value
 * @method tourRoom setLongitude() Sets the current record's "longitude" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetourRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tour_room');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('type', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('latitude', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('longitude', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}