<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adCity', 'doctrine');

/**
 * BaseadCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $countrycode
 * @property string $languagecode
 * @property string $latitude
 * @property string $longitude
 * @property string $name
 * @property integer $nr_hotels
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getCountrycode()  Returns the current record's "countrycode" value
 * @method string  getLanguagecode() Returns the current record's "languagecode" value
 * @method string  getLatitude()     Returns the current record's "latitude" value
 * @method string  getLongitude()    Returns the current record's "longitude" value
 * @method string  getName()         Returns the current record's "name" value
 * @method integer getNrHotels()     Returns the current record's "nr_hotels" value
 * @method adCity  setId()           Sets the current record's "id" value
 * @method adCity  setCountrycode()  Sets the current record's "countrycode" value
 * @method adCity  setLanguagecode() Sets the current record's "languagecode" value
 * @method adCity  setLatitude()     Sets the current record's "latitude" value
 * @method adCity  setLongitude()    Sets the current record's "longitude" value
 * @method adCity  setName()         Sets the current record's "name" value
 * @method adCity  setNrHotels()     Sets the current record's "nr_hotels" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_city');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('countrycode', 'string', 2, array(
             'type' => 'string',
             'default' => 'ad',
             'length' => 2,
             ));
        $this->hasColumn('languagecode', 'string', 2, array(
             'type' => 'string',
             'default' => 'es',
             'length' => 2,
             ));
        $this->hasColumn('latitude', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('longitude', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('nr_hotels', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}