<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adHotelDescription', 'doctrine');

/**
 * BaseadHotelDescription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $descriptiontype_id
 * @property integer $hotel_id
 * @property string $description
 * @property string $languagecode
 * @property adHotel $Hotel
 * @property adHotelDescriptionType $DescType
 * 
 * @method integer                getDescriptiontypeId()  Returns the current record's "descriptiontype_id" value
 * @method integer                getHotelId()            Returns the current record's "hotel_id" value
 * @method string                 getDescription()        Returns the current record's "description" value
 * @method string                 getLanguagecode()       Returns the current record's "languagecode" value
 * @method adHotel                getHotel()              Returns the current record's "Hotel" value
 * @method adHotelDescriptionType getDescType()           Returns the current record's "DescType" value
 * @method adHotelDescription     setDescriptiontypeId()  Sets the current record's "descriptiontype_id" value
 * @method adHotelDescription     setHotelId()            Sets the current record's "hotel_id" value
 * @method adHotelDescription     setDescription()        Sets the current record's "description" value
 * @method adHotelDescription     setLanguagecode()       Sets the current record's "languagecode" value
 * @method adHotelDescription     setHotel()              Sets the current record's "Hotel" value
 * @method adHotelDescription     setDescType()           Sets the current record's "DescType" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadHotelDescription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_hotel_description');
        $this->hasColumn('descriptiontype_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('hotel_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('languagecode', 'string', 2, array(
             'type' => 'string',
             'default' => 'es',
             'length' => 2,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('adHotel as Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id'));

        $this->hasOne('adHotelDescriptionType as DescType', array(
             'local' => 'descriptiontype_id',
             'foreign' => 'id'));
    }
}