<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adHotelRoomPhoto', 'doctrine');

/**
 * BaseadHotelRoomPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $photo_id
 * @property integer $hotel_id
 * @property integer $room_id
 * @property string $small_photo
 * @property string $medium_photo
 * @property string $big_photo
 * @property adHotel $Hotel
 * 
 * @method integer          getId()           Returns the current record's "id" value
 * @method integer          getPhotoId()      Returns the current record's "photo_id" value
 * @method integer          getHotelId()      Returns the current record's "hotel_id" value
 * @method integer          getRoomId()       Returns the current record's "room_id" value
 * @method string           getSmallPhoto()   Returns the current record's "small_photo" value
 * @method string           getMediumPhoto()  Returns the current record's "medium_photo" value
 * @method string           getBigPhoto()     Returns the current record's "big_photo" value
 * @method adHotel          getHotel()        Returns the current record's "Hotel" value
 * @method adHotelRoomPhoto setId()           Sets the current record's "id" value
 * @method adHotelRoomPhoto setPhotoId()      Sets the current record's "photo_id" value
 * @method adHotelRoomPhoto setHotelId()      Sets the current record's "hotel_id" value
 * @method adHotelRoomPhoto setRoomId()       Sets the current record's "room_id" value
 * @method adHotelRoomPhoto setSmallPhoto()   Sets the current record's "small_photo" value
 * @method adHotelRoomPhoto setMediumPhoto()  Sets the current record's "medium_photo" value
 * @method adHotelRoomPhoto setBigPhoto()     Sets the current record's "big_photo" value
 * @method adHotelRoomPhoto setHotel()        Sets the current record's "Hotel" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadHotelRoomPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_hotel_room_photo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('photo_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('hotel_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('room_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('small_photo', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('medium_photo', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('big_photo', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('adHotel as Hotel', array(
             'local' => 'hotel_id',
             'foreign' => 'id'));
    }
}