<?php

/**
 * adCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adCity');
    }
    
    public function getCitiesMain()
    {
      $q = $this->createQuery()->whereIn('id',array(-1394439,-1396418,-1395312,-1395964))->orderBy('RAND()')->fetchArray(); 
      return $q;       
    }
}