<?php

/**
 * adCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adCity');
    }
}