<?php

/**
 * adHotelDescriptionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adHotelDescriptionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adHotelDescriptionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adHotelDescriptionType');
    }
}