<?php

/**
 * adHotelPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adHotelPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adHotelPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adHotelPhoto');
    }
}