<?php

/**
 * adHotelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adHotelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adHotelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adHotel');
    }
}