<?php

/**
 * tourRoomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tourRoomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tourRoomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tourRoom');
    }

    public function getToursMain(){
//      $ht = Doctrine_Core::getTable('adHotel');
//      $ht->createQuery()
//              ->select('COUNT(*)')
//              ->where();
      $q = $this->createQuery();
      $q->whereIn('id',array(9,12,13,11,16,7,10,21,8));
      $q->orderBy('RAND()');
      return $q;

    }
    public function getToursOthers(){
//      $ht = Doctrine_Core::getTable('adHotel');
//      $ht->createQuery()
//              ->select('COUNT(*)')
//              ->where();
      $q = $this->createQuery();
      $q->whereIn('id',array(14,15,17,18,19,4));
//      $q->orderBy('RAND()');
      return $q->fetchArray();

    }
}