# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  max_hotels: 20
  key_map: ABQIAAAAVYTF-_X7joojDMWeD242FxR6RC8zgb2ZGsU4r30MfO7rUTulBRRcQsfjpHEUPXY5cSedlXpbiHC97Q
  aid: 334634



