# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  max_hotels: 15
  key_map: ABQIAAAAVYTF-_X7joojDMWeD242FxR6RC8zgb2ZGsU4r30MfO7rUTulBRRcQsfjpHEUPXY5cSedlXpbiHC97Q
  aid: 334634
  dis_la: 0.008
  dis_lo: 0.008
  city_id: -1456928
  city_un: fr


