# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# pages statics
esqui:
  url: /esqui-andorra
  param: { module: home, action: esqui }
paquetes:
  url: /paquetes-turisticos
  param: { module: home, action: paquetes }
turismo:
  url: /turismo-andorra
  param: { module: home, action: turismo }
excursiones:
  url: /excursiones-actividades
  param: { module: home, action: excursiones }
# pages dinamics
all_hotel:
  url: /hoteles-andorra
  param: { module: home, action: allHotels }
filter_checks:
  url: /filtros/:chk
  param: { module: home, action: filterCheck }
mapa:
  url: /mapa
  param: { module: home, action: mapa }
search:
  url:   /busqueda
  param: { module: home, action: search }
search_city:
  url:  /busqueda-destino
  param: { module: home, action: searchCity }
city:
  url:   /destinos-andorra
  param: { module: home, action: city } 
  
city_hotels:
  url:   /:id/:slug.html
  param: { module: home, action: cityHotels }

city_hotels_result:
  url:   /busqueda/:id/:slug.html
  param: { module: home, action: cityHotelsResult }
hotel_details_result:
  url:   /busqueda/:id/:slug/:slugh.html
  param: { module: home, action: hotelResult }
hotel_details:
  url:   /:id/:slug/:slugh.html
  param: { module: home, action: hotel }
# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
