# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    charset: UTF-8
  metas:
    title:        Andorra Hoteles - Ofertas de Hoteles en Andorra - Reservas de hotel
    description:  Ofertas de hoteles en Andorra. Reservas de hoteles baratos en Andorra para que puedas disfrutar de la temporada de esquí.
    keywords:     hoteles, hotel, andorra, reservar hotel, hoteles en, viajes, viaje, viajar, reservas, ofertas, barato, esqui, ordino, tarter, escaldes"
    language:     es
    #robots:       index, follow

  stylesheets:    [%app_s_css%estilos.css, %app_s_css%estilos_motor_generic.css]

  javascripts:    [%app_s_js%jquery-1.js, %app_s_js%Jfunciones.js]

  has_layout:     true
  layout:         layout
