# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        AndorraHoteles.com - La mejor forma de reservar hotel
    description:  Reserva de hoteles online. Reserva tu hotel en todo el mundo con confirmacion inmediata
    keywords:     hoteles, hotel, reservar hotel, hoteles en, viajes, viaje, viajar, reservas, ofertas, barato
    language:     es
    #robots:       index, follow

  stylesheets:    []

  javascripts:    [%app_s_js%jquery.min.js, %app_s_js%jquery.badBrowser.js, %app_s_js%jquery.tools.min.js]

  has_layout:     true
  layout:         layout
