## YAML Template.
---
all:
  javascripts: [%app_s_js%Jfunciones.js, %app_s_js%search.js]
citySuccess:
  stylesheets: [%app_s_css%reservaria.css]
hotelSuccess:
  stylesheets: [%app_s_css%reservaria.css]
  javascripts: [%app_s_js%imagepreview.js, %app_s_js%search_dispo.js]
hotelResultSuccess:
  stylesheets: [%app_s_css%reservaria.css]
mapaSuccess:
  has_layout: false

excursionesSuccess:
  layout: layout_exc
esquiSuccess:
  layout: layout_esq
paquetesSuccess:
  layout: layout_paq
turismoSuccess:  
  layout: layout_turi
  