## YAML Template.
---
citySuccess:
  stylesheets: [%app_s_css%reservaria.css]
  javascripts: [%app_s_js%jquery.quickpaginate.js]
cityResultSuccess:
  stylesheets: [%app_s_css%reservaria.css]
  javascripts: [%app_s_js%jquery.quickpaginate.js]
hotelSuccess:
  stylesheets: [%app_s_css%reservaria.css]
#  javascripts: [%app_s_js%jquery.quickpaginate.js]
hotelResultSuccess:
  stylesheets: [%app_s_css%reservaria.css]
mapaSuccess:
  has_layout: false