## YAML Template.
---
all:
  stylesheets: [%app_s_css%calendario.css]
  javascripts: [%app_s_js%Jfunciones.js, %app_s_js%search.js, %app_s_js%calendario.js]
hotelSuccess:
  javascripts: [%app_s_js%imagepreview.js, %app_s_js%search_dispo.js]
hotelResultSuccess:
  javascripts: [%app_s_js%imagepreview.js, %app_s_js%search_dispo.js]
mapaSuccess:
  has_layout: false

  